language: python
matrix:
  include:
  - python: 3.6
  - python: 3.7
    dist: xenial
    sudo: true
install:
- pip install tox-travis
script:
- tox
deploy:
  provider: pypi
  server: https://testpypi.python.org/pypi
  user: mmiyajima2
  password: bunbunil2
  skip_cleanup: true
  distributions: sdist bdist_wheel
  on:
    branch: master
    python: 3.7
