language: python

matrix:
  include:
    - python: 3.6
    - python: 3.6
      env: TOXENV=flake8-py3
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install tox-travis

script:
  - tox
