language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install tox-travis

script:
  - tox

deploy:
  provider: pypi
  uesr: mmiyajima2
  password:
    secure: dcZEiEZr6dIKq8mgEZp894FZ7uOf1kKpIaqQ6pFBw+UoxWLGFGuUjBNQ41cCinbTusa6tVrDwOSNUbWRs93K01DyxixfYZlRMKwZH9elQcVMcJvLlBa3FqEWf4DGPALsIKdpYI/m3T7M+is77Wx+uULbllR8O1yw9AFyEGBIG/6fUfff/2lvQiHmDeOxJCFz8R1cK2wiBeSeTO8aIiGzVJ1W9d0RwjrANCKjZIHEsWh/P1puLDxZz2VGfIQa+qb1ZA55MxOn2FD7T1FrZDHnCHm3+BqBu/53ixZYl/Lbn3ZUvDeqowx7dfaq/68QbcHfNfi67lSBKJ/13qkkkAp6Eklwcnu8/L9FZeWuQwTXmCQzbKPE7lfheF6E95swRdAmPsAmbgsFUumJROOEbiky77xyp0Lnv00Rr5io/JCCq4iMt+gPDd/PQ6PTV6qP7CKow5PUU5Cof7NuXs98lDieQSBoarwgaUAgTwnEgojajTa5gyyBZoGnCMhUQ6aNQkAIAJS1HojlwU7dONZ1VW+EjqUdGgEOa4qECdy7Mx0ODhZKu8Rud4BJmyy7FUfu+E4xMZnjaejmk/G7pAJSPaU0DIfLt5OKK7J3NaMVAR62Daunl7fqa8FJ41QzHODmUS9m+Z2rW/ZdCGhi+tQoARnCOtV9kMmRooNnsw9uupQFtxQ=
  on:
    branch: master
