language: python
matrix:
  include:
  - python: 3.6
  - python: 3.7
    dist: xenial
    sudo: true
install:
- pip install tox-travis
script:
- tox
deploy:
  provider: pypi
  server: https://upload.pypi.org/legacy/
  user: mmiyajima2
  password:
    secure: DXMxYB9pnvNio8A+5vCAJZOj2gU/d26bHOirRur0mQ4sAscGTDU05YpIBflOdhE1JqL1XOXWRhXiGPMpZUUB67BQE69MTOaG39Zum3cKFwYoBhGk/SvXfHqsXGJKavavsQu005C5nBagCFq6EJAPFQ/v6X9+YbFWP13IUGd+AAv34nx+vhMw5niaWYUlX7G2oKrwlgQUChWXHbe3VB2RiqpiPmePixgGkyltpoPbSXNqP0O5Z2XrGHHRWz913IUq5d7OF14yjFszuTeTb4wlfexcowLgEziNt9xBjreMp0DjKO3l1tPy56nKUTe3LiGQb+zIzu7ImZ2V682WNeezsMsHmuBltZ8gDHWvFQXJmsHdVTTzQ/vM2SiyCFduz/rj5Spy/r5hs3H0k8guZFs+qTSTmj5Xdd1FUBo4R/HgFDcpAT/Inls5WTCvRx7h1tU3nTLoaOP00zt1JGVe58ljJCcqOT8w9Toh8plrsSGiW4VF70cNRsx7uzbvsK7WaEHjDTTaIvyoxKRaTDegpctixhz5p1m59C+rO0KpoUBZ1NLuB56K/Q9r6nRfXRHI8vvkrqugX21rjLmtpMmtDplClheOWaRBCxmf9AuCeAaokSdjm/qT+tvrszQCzRHsP1HpAGiHQprnnTCVphr5tjUM7nAAycIkwdjafK1skPImIMk=
  skip_cleanup: true
  distributions: sdist bdist_wheel
  on:
    branch: master
    python: 3.7
